name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        python-version:
          - "3.12"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List directory contents
        run: |
          ls -la
          ls -la login_app

      - name: Run unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}/login_app
        run: |
          pytest tests/unit_tests/test_auth_services.py

      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}/login_app
        run: |
          pytest tests/integration_tests/test_auth_router.py
