name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest  # Changed from windows-latest to ubuntu-latest for compatibility with Codecov
        python-version:
          - "3.12"
    name: Test
    runs-on: ${{ matrix.os }}

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Coverage Tools
        run: |
          pip install coverage  # Install coverage tool for reporting
          pip install codecov  # Install Codecov uploader

      - name: Set PYTHONPATH and list directory contents
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "PYTHONPATH is set to %PYTHONPATH%"
          ls -la
          ls -la login_app

      - name: Run unit tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          coverage run -m pytest tests/unit_tests/test_auth_services.py
          coverage report  # Display coverage report in the logs

      - name: Run integration tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          coverage run -m pytest tests/integration_tests/test_auth_router.py
          coverage report  # Display coverage report in the logs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml  # Specify the coverage report file (ensure you generate it)
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional: Provide Codecov token if needed
